### ISSUE TITLE
Fatal Error when starting up Elgg with the theme

### ISSUE THREAD

**Issue by MiToTrade** [fernandovega/time_theme_pro#2]
Fatal Error.

Argument 4 passed to elgg_view_module() must be of the type array, null given, called in /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/views/default/page/layouts/landing_page.php on line 92

TypeError Object
(
[message:protected] => Argument 4 passed to elgg_view_module() must be of the type array, null given, called in /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/views/default/page/layouts/landing_page.php on line 92
[string:Error:private] => TypeError: Argument 4 passed to elgg_view_module() must be of the type array, null given, called in /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/views/default/page/layouts/landing_page.php on line 92 and defined in /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/lib/views.php:1207
Stack trace:
#0 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/views/default/page/layouts/landing_page.php(92): elgg_view_module('featured', '', '<div class="elg...', NULL)
#1 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(362): include('/var/www/vhosts...')
#2 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(300): Elgg\ViewsService->renderViewFile('page/layouts/la...', Array, 'default', true)
#3 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/lib/views.php(343): Elgg\ViewsService->renderView('page/layouts/la...', Array, false, 'default')
#4 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/lib/views.php(699): elgg_view('page/layouts/la...', Array)
#5 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/index.php(62): elgg_view_layout('landing_page', Array)
#6 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/start.php(82): include_once('/var/www/vhosts...')
#7 [internal function]: time_theme_index(Array, '')
#8 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/Router.php(95): call_user_func('time_theme_inde...', Array, '')
#9 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/Application.php(429): Elgg\Router->route(Object(Elgg\Http\Request))
#10 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/Application.php(377): Elgg\Application->run()
#11 /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/index.php(8): Elgg\Application::index()
#12 {main}

[code:protected] => 0
[file:protected] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/lib/views.php
[line:protected] => 1207
[trace:Error:private] => Array
(
[0] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/views/default/page/layouts/landing_page.php
[line] => 92
[function] => elgg_view_module
[args] => Array
(
[0] => featured
[1] =>
[2] => <div class="elgg-module elgg-module-aside"><div class="elgg-head"><h3>Log in</h3></div><div class="elgg-body"><form method="post" action="http://test.pattayaknights.com/action/login" class="elgg-form-login elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden">

<div>
<label>Username or email</label>
<input value="" type="text" name="username" id="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label>
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" required="" class="elgg-input-password"></div>

<div class="elgg-foot">
<label class="mtm float-alt">
<input type="checkbox" name="persistent" value="true" />
Remember me </label>

<input type="submit" value="Log in" class="elgg-button-submit elgg-button">

<ul class="elgg-menu elgg-menu-login elgg-menu-general elgg-menu-hz mtm elgg-menu-login-default"><li class="elgg-menu-item-forgotpassword"><a class="elgg-menu-content forgot_link" href="http://elgg_1.12/forgotpassword">Lost password</a></li></ul>
</div>

</fieldset></form></div></div>
[3] =>
)

)

[1] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 362
[args] => Array
(
[0] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/views/default/page/layouts/landing_page.php
)

[function] => include
)

[2] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 300
[function] => renderViewFile
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/layouts/landing_page
[1] => Array
(
[blogs] =>
[groups] =>
[login] => <div class="elgg-module elgg-module-aside"><div class="elgg-head"><h3>Log in</h3></div><div class="elgg-body"><form method="post" action="http://test.pattayaknights.com/action/login" class="elgg-form-login elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden">

<div>
<label>Username or email</label>
<input value="" type="text" name="username" id="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label>
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" required="" class="elgg-input-password"></div>

<div class="elgg-foot">
<label class="mtm float-alt">
<input type="checkbox" name="persistent" value="true" />
Remember me </label>

<input type="submit" value="Log in" class="elgg-button-submit elgg-button">

<ul class="elgg-menu elgg-menu-login elgg-menu-general elgg-menu-hz mtm elgg-menu-login-default"><li class="elgg-menu-item-forgotpassword"><a class="elgg-menu-content forgot_link" href="http://elgg_1.12/forgotpassword">Lost password</a></li></ul>
</div>

</fieldset></form></div></div>
[register] => <form method="post" action="http://test.pattayaknights.com/action/register" class="elgg-form-account elgg-form-register elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden"><div class="mtm">
<label>Display name</label><br />
<input type="text" name="name" required="" class="elgg-input-text"></div>

<div>
<label>Email address</label><br />
<input type="text" name="email" id="email" required="" class="elgg-input-text"></div>
<div>
<label>Username</label><br />
<input type="text" name="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" id="password" required="" class="elgg-input-password"></div>
<div>
<label>Password (again for verification)</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password2" id="password2" required="" class="elgg-input-password"></div>

<div class="elgg-foot"><input name="friend_guid" type="hidden"><input name="invitecode" type="hidden"><input type="submit" name="submit" value="Register" class="elgg-button-submit elgg-button"></div></fieldset></form>
[members] =>
[layout] => landing_page
)

[2] => default
[3] => 1
)

)

[3] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/lib/views.php
[line] => 343
[function] => renderView
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/layouts/landing_page
[1] => Array
(
[blogs] =>
[groups] =>
[login] => <div class="elgg-module elgg-module-aside"><div class="elgg-head"><h3>Log in</h3></div><div class="elgg-body"><form method="post" action="http://test.pattayaknights.com/action/login" class="elgg-form-login elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden">
<div>
<label>Username or email</label>
<input value="" type="text" name="username" id="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label>
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" required="" class="elgg-input-password"></div>

<div class="elgg-foot">
<label class="mtm float-alt">
<input type="checkbox" name="persistent" value="true" />
Remember me </label>

<input type="submit" value="Log in" class="elgg-button-submit elgg-button">

<ul class="elgg-menu elgg-menu-login elgg-menu-general elgg-menu-hz mtm elgg-menu-login-default"><li class="elgg-menu-item-forgotpassword"><a class="elgg-menu-content forgot_link" href="http://elgg_1.12/forgotpassword">Lost password</a></li></ul>
</div>

</fieldset></form></div></div>
[register] => <form method="post" action="http://test.pattayaknights.com/action/register" class="elgg-form-account elgg-form-register elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden"><div class="mtm">
<label>Display name</label><br />
<input type="text" name="name" required="" class="elgg-input-text"></div>

<div>
<label>Email address</label><br />
<input type="text" name="email" id="email" required="" class="elgg-input-text"></div>
<div>
<label>Username</label><br />
<input type="text" name="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" id="password" required="" class="elgg-input-password"></div>
<div>
<label>Password (again for verification)</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password2" id="password2" required="" class="elgg-input-password"></div>

<div class="elgg-foot"><input name="friend_guid" type="hidden"><input name="invitecode" type="hidden"><input type="submit" name="submit" value="Register" class="elgg-button-submit elgg-button"></div></fieldset></form>
[members] =>
[layout] => landing_page
)

[2] =>
[3] => default
)

)

[4] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/lib/views.php
[line] => 699
[function] => elgg_view
[args] => Array
(
[0] => page/layouts/landing_page
[1] => Array
(
[blogs] =>
[groups] =>
[login] => <div class="elgg-module elgg-module-aside"><div class="elgg-head"><h3>Log in</h3></div><div class="elgg-body"><form method="post" action="http://test.pattayaknights.com/action/login" class="elgg-form-login elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden">
<div>
<label>Username or email</label>
<input value="" type="text" name="username" id="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label>
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" required="" class="elgg-input-password"></div>

<div class="elgg-foot">
<label class="mtm float-alt">
<input type="checkbox" name="persistent" value="true" />
Remember me </label>

<input type="submit" value="Log in" class="elgg-button-submit elgg-button">

<ul class="elgg-menu elgg-menu-login elgg-menu-general elgg-menu-hz mtm elgg-menu-login-default"><li class="elgg-menu-item-forgotpassword"><a class="elgg-menu-content forgot_link" href="http://elgg_1.12/forgotpassword">Lost password</a></li></ul>
</div>

</fieldset></form></div></div>
[register] => <form method="post" action="http://test.pattayaknights.com/action/register" class="elgg-form-account elgg-form-register elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden"><div class="mtm">
<label>Display name</label><br />
<input type="text" name="name" required="" class="elgg-input-text"></div>

<div>
<label>Email address</label><br />
<input type="text" name="email" id="email" required="" class="elgg-input-text"></div>
<div>
<label>Username</label><br />
<input type="text" name="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" id="password" required="" class="elgg-input-password"></div>
<div>
<label>Password (again for verification)</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password2" id="password2" required="" class="elgg-input-password"></div>

<div class="elgg-foot"><input name="friend_guid" type="hidden"><input name="invitecode" type="hidden"><input type="submit" name="submit" value="Register" class="elgg-button-submit elgg-button"></div></fieldset></form>
[members] =>
[layout] => landing_page
)

)

)

[5] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/index.php
[line] => 62
[function] => elgg_view_layout
[args] => Array
(
[0] => landing_page
[1] => Array
(
[blogs] =>
[groups] =>
[login] => <div class="elgg-module elgg-module-aside"><div class="elgg-head"><h3>Log in</h3></div><div class="elgg-body"><form method="post" action="http://test.pattayaknights.com/action/login" class="elgg-form-login elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden">
<div>
<label>Username or email</label>
<input value="" type="text" name="username" id="username" required="" class="elgg-input-text"></div>
<div>
<label>Password</label>
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" required="" class="elgg-input-password"></div>

<div class="elgg-foot">
<label class="mtm float-alt">
<input type="checkbox" name="persistent" value="true" />
Remember me </label>

<input type="submit" value="Log in" class="elgg-button-submit elgg-button">

<ul class="elgg-menu elgg-menu-login elgg-menu-general elgg-menu-hz mtm elgg-menu-login-default"><li class="elgg-menu-item-forgotpassword"><a class="elgg-menu-content forgot_link" href="http://elgg_1.12/forgotpassword">Lost password</a></li></ul>
</div>

</fieldset></form></div></div>
[register] => <form method="post" action="http://test.pattayaknights.com/action/register" class="elgg-form-account elgg-form-register elgg-form"><fieldset><input name="__elgg_token" value="Pk_nbkjgr36If7TFZgwyVQ" type="hidden"><input name="__elgg_ts" value="1476148429" type="hidden"><div class="mtm">
<label>Display name</label><br />
<input type="text" name="name" required="" class="elgg-input-text"></div>

<div>
<label>Email address</label><br />
<input type="text" name="email" id="email" required="" class="elgg-input-text"></div>

<div>
<label>Username</label><br />
<input type="text" name="username" required="" class="elgg-input-text"></div>

<div>
<label>Password</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password" id="password" required="" class="elgg-input-password"></div>

<div>
<label>Password (again for verification)</label><br />
<input value="" autocapitalize="off" autocorrect="off" type="password" name="password2" id="password2" required="" class="elgg-input-password"></div>

<div class="elgg-foot"><input name="friend_guid" type="hidden"><input name="invitecode" type="hidden"><input type="submit" name="submit" value="Register" class="elgg-button-submit elgg-button"></div></fieldset></form>
[members] =>
)

)

)

[6] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/start.php
[line] => 82
[args] => Array
(
[0] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/mod/time_theme_pro/index.php
)

[function] => include_once
)

[7] => Array
(
[function] => time_theme_index
[args] => Array
(
[0] => Array
(
)

[1] =>
)

)

[8] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/Router.php
[line] => 95
[function] => call_user_func
[args] => Array
(
[0] => time_theme_index
[1] => Array
(
)

[2] =>
)

)

[9] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/Application.php
[line] => 429
[function] => route
[class] => Elgg\Router
[type] => ->
[args] => Array
(
[0] => Elgg\Http\Request Object
(
[attributes] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[request] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[query] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_uri] => /
)

)

[server] => Symfony\Component\HttpFoundation\ServerBag Object
(
[parameters:protected] => Array
(
[PATH] => /sbin:/usr/sbin:/bin:/usr/bin
[PP_CUSTOM_PHP_INI] => /var/www/vhosts/system/test.pattayaknights.com/etc/php.ini
[PP_CUSTOM_PHP_CGI_INDEX] => plesk-php70-fastcgi
[SCRIPT_NAME] => /index.php
[REQUEST_URI] => /
[QUERY_STRING] =>
[REQUEST_METHOD] => GET
[SERVER_PROTOCOL] => HTTP/1.0
[GATEWAY_INTERFACE] => CGI/1.1
[REMOTE_PORT] => 48913
[SCRIPT_FILENAME] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/index.php
[SERVER_ADMIN] => admin@mito-trading.com
[DOCUMENT_ROOT] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com
[REMOTE_ADDR] => 171.5.182.55
[SERVER_PORT] => 80
[SERVER_ADDR] => 5.199.133.159
[SERVER_NAME] => test.pattayaknights.com
[SERVER_SOFTWARE] => Apache
[SERVER_SIGNATURE] => <address>Apache Server at test.pattayaknights.com Port 80</address>

[HTTP_UPGRADE_INSECURE_REQUESTS] => 1
[HTTP_DNT] => 1
[HTTP_COOKIE] => Elgg_install=sgc75eqkg6t4lduirj81d6qcl5; Elgg=faa8a9g0p0q8d5h6b2kmdraau0
[HTTP_REFERER] => http://test.pattayaknights.com/admin/plugins
[HTTP_ACCEPT_ENCODING] => gzip, deflate
[HTTP_ACCEPT_LANGUAGE] => de,en-US;q=0.7,en;q=0.3
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
[HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
[HTTP_CONNECTION] => close
[HTTP_X_ACCEL_INTERNAL] => /internal-nginx-static-location
[HTTP_X_FORWARDED_FOR] => 171.5.182.55
[HTTP_X_REAL_IP] => 171.5.182.55
[HTTP_HOST] => test.pattayaknights.com
[FCGI_ROLE] => RESPONDER
[PHP_SELF] => /index.php
[REQUEST_TIME_FLOAT] => 1476148429.2597
[REQUEST_TIME] => 1476148429
)

)

[files] => Symfony\Component\HttpFoundation\FileBag Object
(
[parameters:protected] => Array
(
)

)

[cookies] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[Elgg_install] => sgc75eqkg6t4lduirj81d6qcl5
[Elgg] => faa8a9g0p0q8d5h6b2kmdraau0
)

)

[headers] => Symfony\Component\HttpFoundation\HeaderBag Object
(
[headers:protected] => Array
(
[upgrade-insecure-requests] => Array
(
[0] => 1
)

[dnt] => Array
(
[0] => 1
)

[cookie] => Array
(
[0] => Elgg_install=sgc75eqkg6t4lduirj81d6qcl5; Elgg=faa8a9g0p0q8d5h6b2kmdraau0
)

[referer] => Array
(
[0] => http://test.pattayaknights.com/admin/plugins
)

[accept-encoding] => Array
(
[0] => gzip, deflate
)

[accept-language] => Array
(
[0] => de,en-US;q=0.7,en;q=0.3
)

[accept] => Array
(
[0] => text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
)

[user-agent] => Array
(
[0] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
)

[connection] => Array
(
[0] => close
)

[x-accel-internal] => Array
(
[0] => /internal-nginx-static-location
)

[x-forwarded-for] => Array
(
[0] => 171.5.182.55
)

[x-real-ip] => Array
(
[0] => 171.5.182.55
)

[host] => Array
(
[0] => test.pattayaknights.com
)

)

[cacheControl:protected] => Array
(
)

)

[content:protected] =>
[languages:protected] =>
[charsets:protected] =>
[encodings:protected] =>
[acceptableContentTypes:protected] =>
[pathInfo:protected] =>
[requestUri:protected] => /
[baseUrl:protected] =>
[basePath:protected] =>
[method:protected] =>
[format:protected] =>
[session:protected] =>
[locale:protected] =>
[defaultLocale:protected] => en
)

)

)

[10] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/vendor/elgg/elgg/engine/classes/Elgg/Application.php
[line] => 377
[function] => run
[class] => Elgg\Application
[type] => ->
[args] => Array
(
)

)

[11] => Array
(
[file] => /var/www/vhosts/pattayaknights.com/subs/test.pattayaknights.com/index.php
[line] => 8
[function] => index
[class] => Elgg\Application
[type] => ::
[args] => Array
(
)

)

)

[previous:Error:private] =>
)

**Comment by MiToTrade** [comment]
No idea how to solve that. I tried it with a freshly installed elgg-test-environment...but same

**Comment by dominicanfunrd** [comment]
Bueno, un amigo mio ingeniero de programacion dice que hay mil errores en el java de este theme, que se tarda menos en crear uno nuevo que resolver ese, no pierdan el tiempo. da fallos el extender el perfil, el instalar un chat, etc....

**Comment by dominicanfunrd** [comment]
incluso te obliga a entrar con la direccion tudominio.com/activity en lugar dle dominio.com solamente, no deja instalar reproductores, da fallos de compatibilidad con tidipics... lastima porque es un tema lindisimo, pero......

**Comment by MiToTrade** [comment]
Thx a lot for your revealing answers. Good i can at least read spanish as i speak italian and portuguese very well also. I already found another theme that is working and will drop this one... Thx again.

**Comment by fernandovega** [comment]
Eliminare la pagina de landing page, es la responsable de estos errores, estoy trabajando en las correciones. Saludos

**Comment by huantino** [comment]
Hola Fernando. ¿Para cuando crees que tendrás las correcciones? Saludos.
